# Extra autostart processes
# exec-once = uwsm-app -- my-service


# exec-once = hyprmode-daemon (Disabled: already started by systemd user service)
# Set wallpapers (workspace-specific)
exec-once = chmod +x ~/scripts/apply_last_wallpaper.sh && ~/scripts/apply_last_wallpaper.sh
# exec-once = ~/.config/hypr/scripts/workspace-wallpaper.sh

# Valent (KDE Connect implementation for Wayland)
# exec-once = valent

exec-once = mpd
exec-once = ~/.config/hypr/scripts/monitor_listener.sh
