source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/lid-switch.conf
source = ~/.local/state/omarchy/toggles/hypr/*.conf
fullscreen = 1
# Cursor Theme
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_SIZE,24

# Force GTK apps to use the theme as well
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = mako
exec-once = swaync

# Hyprland Plugins
plugin = /home/ashish/.config/hypr/plugins/libhyprexpo.so

plugin {
    hyprexpo {
        columns = 2
        gap_size = 5
        bg_col = rgb(111111)
    }
}
