
# HyprMode - Float and center (for Ghostty)
windowrule = float on, center on, size 600 530, opacity 0.95, match:title ^(hyprmode)$

# HyprMode - Float and center (for Alacritty)
windowrule = float on, center on, size 600 530, opacity 0.95, match:class ^(hyprmode)$

# Night Light Slider popup
windowrule = float, title:^(Night Light Slider)$
windowrule = center, title:^(Night Light Slider)$
windowrule = size 350 200, title:^(Night Light Slider)$
windowrule = stayfocused, title:^(Night Light Slider)$

# Scratchpad rules (Special Workspace)
windowrule = float, special:magic
windowrule = center, special:magic
windowrule = size 80% 80%, special:magic
windowrule = opacity 0.95, special:magic
